name: Code Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
      - name: Enable Corepack
        run: corepack enable
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint:check
      - name: Build
        run: yarn build
